name = "MathieuFunctions"
uuid = "9663349c-1c87-11ea-291d-bd81f86a413c"
authors = ["Marcus P da Silva", "Daniel Greenbaum", "John Lapeyre", "Matthew Ware"]
version = "1.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1"

[extras]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["DelimitedFiles", "Test"]
