name: Codecov
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  coverage:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@master
      - uses: codecov/codecov-action@v1.1.1
        with:
          file: ./lcov.info # optional
          flags: unittests # optional
          name: codecov-umbrella # optional
          fail_ci_if_error: false # optional (default = false)
          verbose: true # optional (default = false)
